config/routes.rb
Rails.application.routes.draw do
  resources :customers do
    resources :interactions
  end

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  resource :user, only: [:edit, :update]

  get 'permissions/denied' => 'permissions#denied', as: 'permissions_denied'

  root to: 'customers#index'

end

app/controllers/interactions_controller.rb
class InteractionsController < ApplicationController
  before_action :set_customer
  load_and_authorize_resource only: [:show, :edit, :update, :destroy]

  # GET /customer/1/interactions
  # GET /customer/1/interactions.json
  def index
    redirect_to @customer
  end

  # GET /customer/1/interactions/1
  # GET /customer/1/interactions/1.json
  def show
    redirect_to @customer
  end

  # GET /customers/1/interactions/new
  def new
    @interaction = Interaction.new
  end

  # GET /customer/1/interactions/1/edit
  def edit
  end

  # POST /customer/1/interactions
  # POST /customer/1/interactions.json
  def create
    @interaction = Interaction.new(interaction_params)
    @interaction.customer = @customer

    respond_to do |format|
      if @interaction.save
        check_next_contact
        format.html { redirect_to [@customer, @interaction], notice: 'Interaction was successfully created.' }
        format.json { render :show, status: :created, location: @interaction }
      else
        format.html { render :new }
        format.json { render json: @interaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customer/1/interactions/1
  # PATCH/PUT /customer/1/interactions/1.json
  def update
    respond_to do |format|
      if @interaction.update(interaction_params)
        check_next_contact
        format.html { redirect_to [@customer, @interaction], notice: 'Interaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @interaction }
      else
        format.html { render :edit }
        format.json { render json: @interaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customer/1/interactions/1
  # DELETE /customer/1/interactions/1.json
  def destroy
    @interaction.destroy
    respond_to do |format|
      format.html { redirect_to @customer, notice: 'Interaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_customer
      @customer = Customer.find(params[:customer_id])
      authorize! :read, @customer
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def interaction_params
      params.require(:interaction).permit(:time, :mode, :description)
    end

    def check_next_contact
      if @interaction.time > DateTime.now
        @customer.next_contact = DateTime.now if @interaction.time > DateTime.now
        @customer.save
      end
    end
end

app/helpers/interactions_helper.rb
module InteractionsHelper
end

app/views/interactions/_form.html.erb
<%= form_for [@customer, @interaction] do |f| %>
  <% if @interaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@interaction.errors.count, "error") %> prohibited this interaction from being saved:</h2>

      <ul>
      <% @interaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :time %><br>
    <%= f.datetime_select :time %>
  </div>
  <div class="form-group">
    <%= f.label :mode %><br>
    <%= f.select :mode, options_for_select(Interaction.modes.map {|j,k| [j.humanize, j]}, @interaction.mode), class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-success' %>
    <%= link_to 'Back', customer_interactions_path(@customer), class: 'btn btn-default' %>
  </div>
<% end %>

app/views/interactions/edit.html.erb
<h2>Editing Interaction</h2>

<%= render 'form' %>

app/views/interactions/new.html.erb
<h2>New Interaction</h2>

<%= render 'form' %>