config/routes.rb
Rails.application.routes.draw do
  resources :customers do
    resources :interactions
  end

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  resource :user, only: [:edit, :update]

  get 'permissions/denied' => 'permissions#denied', as: 'permissions_denied'

  root to: 'customers#index'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :user
  has_many :interactions, dependent: :destroy

  validates :name, presence: true, uniqueness: {scope: :user}

  def self.active(customers, city_country)
    customers.find_all { |customer| customer.active?(city_country) }
  end

  def self.inactive(customers, city_country)
    customers.find_all { |customer| !customer.active?(city_country) }
  end

  def active?(user_city_country)
    different_city = !user_city_country.nil? && !user_city_country.empty? &&
                     !city_country.nil? && !city_country.empty? &&
                     user_city_country != city_country
    status != :termination && !different_city
  end

  def status
    status = Interaction.where(customer: self).order('mode DESC').limit(1).first
    ((status && status.mode) || Interaction.modes.first[0]).to_sym
  end

  def next_contact
    return nil if terminated?
    dbval = read_attribute(:next_contact)
    return dbval if dbval && dbval > DateTime.now

    return nil if !next_interaction.nil?
    last_interaction = interactions.order('time ASC').first
    time = last_interaction && last_interaction.time || DateTime.now.utc
    return time + 5.days
  end

  def next_interaction
    interaction = interactions.where("time > ?", DateTime.now).order('time ASC').first
    interaction && interaction.time
  end

  private
    def terminated?
      interactions.find { |interaction| interaction.mode.to_sym == :termination }
    end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  load_and_authorize_resource only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @active_customers = Customer.active(current_user.customers, current_user.city_country)
    @inactive_customers = Customer.inactive(current_user.customers, current_user.city_country)
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)
    @customer.user = current_user

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:name, :next_contact, :quality, :city_country, :description)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
  def gray_out_inaccessible(customer)
    customer.active?(current_user.city_country) ? '' : 'class=inaccessible'
  end

  def status_color(status)
    colors = {
      communication: 'active',
      meeting: 'info',
      cancelation: 'warning',
      close: 'success',
      termination: 'danger'
    }
    colors[status]
  end

  def quality_color(quality)
    return "transparent" if quality.nil?
    red = 200 - 20*quality
    green = 20*quality
    "rgba(#{red}, #{green}, 0, 0.3)"
  end

  def interaction_color(interaction, past=false)
    return "" if interaction.nil? or interaction - DateTime.now < 0
    return 'info' if interaction - DateTime.now <= 2.days
    nil
  end
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control', required: true %>
  </div>
  <div class="form-group">
    <%= f.label :next_contact %><br>
    <%= f.datetime_select :next_contact %>
  </div>
  <div class="form-group">
    <%= f.label :quality %><br>
    <%= f.number_field :quality, in: [1, 10], class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :city_country, 'City, Country (e.g. Toronto, Canada)' %><br>
    <%= f.text_field :city_country, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-success' %>
    <%= link_to 'Back', customers_path, class: 'btn btn-default' %>
  </div>
<% end %>

app/views/customers/_list.html.erb
<h2>
  <%= title %>

  <% if !local_assigns[:create].nil? && create %>
    <%= link_to 'New Customer', new_customer_path, class: 'btn btn-success pull-right' %>
  <% end %>
</h2>
<hr class="soften" />

<table class="table sortable">
  <thead>
    <tr>
      <th>Name</th>
      <th>Status</th>
      <th>Contact reminder</th>
      <th data-defaultsort="asc">Next scheduled interaction</th>
      <th>Quality</th>
      <th>City, Country</th>
      <th>Description</th>
      <th data-defaultsort="disabled"></th>
    </tr>
  </thead>

  <tbody>
    <% customers.each do |customer| %>
      <tr <%= gray_out_inaccessible(customer) %>>
        <td><%= link_to customer.name, customer %></td>
        <td class="<%= status_color(customer.status) %>"><%= customer.status.to_s.humanize %></td>
        <td class="<%= interaction_color(customer.next_contact, past: true) %>" data-value="<%= customer.next_contact || 'ZZZ' %>">
          <%= local_time(customer.next_contact) if !customer.next_contact.nil? %>
        </td>
        <td class="<%= interaction_color(customer.next_interaction) %>" data-value="<%= customer.next_interaction || 'ZZZ' %>">
          <%= local_time(customer.next_interaction, type: 'weekday-or-date') if !customer.next_interaction.nil? %>
        </td>
        <td style="color: white; background: <%= quality_color(customer.quality) %>"><%= customer.quality %></td>
        <td><%= customer.city_country %></td>
        <td><%= truncate customer.description, length: 30 %></td>
        <td class="text-right">
          <%= link_to 'Show', customer, class: 'btn btn-info btn-xs' %>
          <%= link_to 'Edit', edit_customer_path(customer), class: 'btn btn-primary btn-xs' %>
          <%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/customers/edit.html.erb
<h2>Editing Customer</h2>

<%= render 'form' %>

app/views/customers/index.html.erb
<% if notice %>
  <div class="alert alert-info"><%= notice %></div>
<% end %>

<%= render 'list', title: 'Active Customers', customers: @active_customers, create: true %>

<% if @inactive_customers.length > 0 %>
  <%= render 'list', title: 'Inactive Customers', customers: @inactive_customers %>
<% end %>

app/views/customers/new.html.erb
<h2>New Customer</h2>

<%= render 'form' %>

app/views/customers/show.html.erb
<% if notice %>
  <div class="alert alert-info"><%= notice %></div>
<% end %>

<h2><%= @customer.name %></h2>

<table class="table">
  <thead>
    <tr>
      <th>Status</th>
      <th>Contact reminder</th>
      <th>Next scheduled interaction</th>
      <th>Quality</th>
      <th>City, Country</th>
    </tr>
  </thead>

  <tbody>
    <td class="<%= status_color(@customer.status) %>"><%= @customer.status.to_s.humanize %></td>
    <td class="<%= interaction_color(@customer.next_contact, past: true) %>" data-value="<%= @customer.next_contact || 'ZZZ' %>">
      <%= local_time(@customer.next_contact) if !@customer.next_contact.nil? %>
    </td>
    <td class="<%= interaction_color(@customer.next_interaction) %>" data-value="<%= @customer.next_interaction || 'ZZZ' %>">
      <%= local_time(@customer.next_interaction) if !@customer.next_interaction.nil? %>
    </td>
    <td style="color: white; background: <%= quality_color(@customer.quality) %>"><%= @customer.quality %></td>
    <td><%= @customer.city_country %></td>
  </tbody>
</table>

<% if !@customer.description.nil? && !@customer.description.empty? %>
  <div class="row">
    <div class="col-sm-6">
      <div class="panel panel-default">
        <div class="panel-heading">
          Description
        </div>
        <div class="panel-body">
          <%= @customer.description %>
        </div>
      </div>
    </div>
  </div>
<% end %>

<%= link_to 'Edit', edit_customer_path(@customer), class: 'btn btn-primary' %> |
<%= link_to 'Back', customers_path, class: 'btn btn-default' %>

<hr class="soften" />

<h2>Interactions <%= link_to 'New Interaction', new_customer_interaction_path(@customer), class: 'btn btn-success pull-right' %></h2>

<table class="table sortable">
  <thead>
    <tr>
      <th data-defaultsort="desc">Time</th>
      <th>Mode</th>
      <th>Description</th>
      <th data-defaultsort="disabled"></th>
    </tr>
  </thead>

  <tbody>
    <% @customer.interactions.each do |interaction| %>
      <tr>
        <td class="<%= interaction_color(interaction.time) %>">
          <%= local_time(interaction.time) if !interaction.time.nil? %>
        </td>
        <td class="<%= status_color(interaction.mode.to_sym) %>"><%= interaction.mode.humanize %></td>
        <td><%= interaction.description %></td>
        <td class="text-right">
          <%= link_to 'Edit', edit_customer_interaction_path(@customer, interaction), class: 'btn btn-primary btn-xs' %>
          <%= link_to 'Destroy', customer_interaction_path(@customer, interaction), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>